// This file is generated by next-typesafe-url
// Do not edit this file directly.

// @generated
// prettier-ignore
/* eslint-disable */


declare module "@@@next-typesafe-url" {
  import type { InferRoute, StaticRoute } from "next-typesafe-url";
  
  interface DynamicRouter {
  
  }

  interface StaticRouter {
    "/404": StaticRoute;
    "/451": StaticRoute;
    "/add/[[...currency]]": StaticRoute;
    "/bridge": StaticRoute;
    "/create-profile": StaticRoute;
    "/find": StaticRoute;
    "/home": StaticRoute;
    "/ido": StaticRoute;
    "/ido/w3w": StaticRoute;
    "/ido/[ido]": StaticRoute;
    "/ifo/history": StaticRoute;
    "/ifo": StaticRoute;
    "/increase/[[...currency]]": StaticRoute;
    "/": StaticRoute;
    "/info": StaticRoute;
    "/info/infinity": StaticRoute;
    "/info/infinity/tokens": StaticRoute;
    "/info/infinity/tokens/[address]": StaticRoute;
    "/info/infinity/[chainName]": StaticRoute;
    "/info/infinity/[chainName]/pairs": StaticRoute;
    "/info/infinity/[chainName]/tokens": StaticRoute;
    "/info/infinity/[chainName]/tokens/[address]": StaticRoute;
    "/info/pairs": StaticRoute;
    "/info/pairs/[address]": StaticRoute;
    "/info/tokens/[address]": StaticRoute;
    "/info/tokens": StaticRoute;
    "/info/v3": StaticRoute;
    "/info/v3/pairs": StaticRoute;
    "/info/v3/pairs/[address]": StaticRoute;
    "/info/v3/tokens": StaticRoute;
    "/info/v3/tokens/[address]": StaticRoute;
    "/info/v3/[chainName]": StaticRoute;
    "/info/v3/[chainName]/pairs": StaticRoute;
    "/info/v3/[chainName]/pairs/[address]": StaticRoute;
    "/info/v3/[chainName]/tokens": StaticRoute;
    "/info/v3/[chainName]/tokens/[address]": StaticRoute;
    "/info/[chainName]": StaticRoute;
    "/info/[chainName]/pairs": StaticRoute;
    "/info/[chainName]/pairs/[address]": StaticRoute;
    "/info/[chainName]/tokens/[address]": StaticRoute;
    "/info/[chainName]/tokens": StaticRoute;
    "/invite/[code]": StaticRoute;
    "/limit-orders": StaticRoute;
    "/lottery": StaticRoute;
    "/mev": StaticRoute;
    "/migration/bcake": StaticRoute;
    "/migration": StaticRoute;
    "/nfts/activity": StaticRoute;
    "/nfts/collections": StaticRoute;
    "/nfts/collections/[collectionAddress]/[tokenId]": StaticRoute;
    "/nfts/collections/[collectionAddress]": StaticRoute;
    "/nfts": StaticRoute;
    "/pancake-squad": StaticRoute;
    "/pools/history": StaticRoute;
    "/pools": StaticRoute;
    "/pools/[chainName]/[id]": StaticRoute;
    "/position-managers/[[...slug]]": StaticRoute;
    "/pottery": StaticRoute;
    "/prediction": StaticRoute;
    "/prediction/leaderboard": StaticRoute;
    "/profile": StaticRoute;
    "/profile/pancake-collectibles": StaticRoute;
    "/profile/[accountAddress]/achievements": StaticRoute;
    "/profile/[accountAddress]/activity": StaticRoute;
    "/profile/[accountAddress]": StaticRoute;
    "/remove/[tokenId]": StaticRoute;
    "/stable/add/[[...currency]]": StaticRoute;
    "/stable/remove/[[...currency]]": StaticRoute;
    "/stable/[address]": StaticRoute;
    "/swap": StaticRoute;
    "/swap/limit": StaticRoute;
    "/swap/twap": StaticRoute;
    "/teams": StaticRoute;
    "/teams/[id]": StaticRoute;
    "/terms-of-service": StaticRoute;
    "/v2/add/[[...currency]]": StaticRoute;
    "/v2/migrate/[address]": StaticRoute;
    "/v2/pair/[[...currency]]": StaticRoute;
    "/v2/remove/[[...currency]]": StaticRoute;
  }
}
